### ISSUE TITLE
Edit/delete messages

### ISSUE THREAD

**Issue by towerofnix** [decent-chat/decent#115]
Each message should have a way to open a dropdown (probably an ellipsis-button to the side) letting the user edit or delete it.

* Edit (if the user owns the message). See #58 for old discussion on how editing a message should work. @PullJosh? On Gitter and Discord, editing a message replaces the message's content with an input box for typing in; that seems the most intuitive to me. (Also, it doesn't remove existing content from the chat input - it creates a *new* input.)

* Delete (if the user owns the message, or is an admin). Should there be a confirmation dialog?

The actual dropdown should be implemented as a "separate" unit - other functions should be able to easily use the same dropdown code. I'm thinking there should be a global dropdown element which is filled/shown by a `showDropdown` function, that way we don't need to create and keep track of tooooooooooons of DOM elements (a dropdown and its items for every single message sent!).

**Comment by PullJosh** [comment]
A few thoughts:
* Should there be checkboxes next to messages for admins so that they can mass-delete messages?
* The ideal UI for deleting messages would be to have a button which performs the action instantly (no confirmation modal), but then gives you an option to undo (a la gmail). No idea whether this is feasible API-wise though.

**Comment by heyitsmeuralex** [comment]
>Should there be checkboxes next to messages for admins so that they can mass-delete messages?

Eh, that doesn't seem fun. We can do shift-clicking on messages to select, though - I feel like that's better than a checkbox.

**Comment by heyitsmeuralex** [comment]
>but then gives you an option to undo. No idea whether this is feasible API-wise though

If we just set a flag (`{ deleted: true }`) on a message when we delete it, we can keep all metadata about that message. The server should just never send messages where `deleted: true` to clients.

**Comment by PullJosh** [comment]
Would there be any benefit to creating two different options: "delete" and "hide"?

Delete could require a modal confirmation and be permanent, while "hide" just triggers a "hidden" boolean which makes the message invisible to regular users and collapsed and/or faded out for admins.

No idea if that would be better, just something that came to mind.

**Comment by heyitsmeuralex** [comment]
I don't think that's worth it.

**Comment by towerofnix** [comment]
Mind you, I want there to be *some* means of permanently deleting messages - as in, actually removing them from the database. Leaving them there (even if they're only internally stored and can't be fetched) seems like a breach of trust in what "deleting" means.

One option is to have a set amount of time after which messages are permanently deleted (server setting/property).

**Comment by heyitsmeuralex** [comment]
We'd want to delete old image uploads too.

**Comment by towerofnix** [comment]
@PullJosh Assuming the server stays persistently running, just remove every message with a "to be deleted on (date)" less than the current date every 30 minutes or such.
