### ISSUE TITLE
Holding alt and pressing the up/down keys should navigate channels

### ISSUE THREAD

**Issue by towerofnix** [decent-chat/decent#13]
Ala Discord and Riot.

**Comment by towerofnix** [comment]
Assigning to @heyitsmeuralex but you can not do this and replace with help wanted if you want :^)

**Comment by towerofnix** [comment]
@heyitsmeuralex I noticed that just pressing up/down also changes the channel. I think it should be limited to holding alt at the same time, since up/down could be used to move around the chat input box. (Sure, we could prevent keyboard events from bubbling from the text box, but that's not good either - after all, 99% of the time the user is focused in it. Keyboard shortcuts should be non-intrusive with editing.)

**Comment by heyitsmeuralex** [comment]
> I noticed that just pressing up/down also changes the channel

What the heck; that's a bug. Unintended.

**Comment by towerofnix** [comment]
Reopening - I can now press alt-up/down to navigate the channel list, *but only if the chat input is unselected*. Since the chat input is selected 99% of the time, alt-up/down should work while it's selected.

**Comment by heyitsmeuralex** [comment]
That's a mousetrap thing - I thought you'd mention it.

**Comment by towerofnix** [comment]
Reopening - this is not implemented in the new client.
