### ISSUE TITLE
Convert messages component into a nanocomponent for stability

### ISSUE THREAD

**Issue by heyitsmeuralex** [decent-chat/decent#137]
See https://github.com/choojs/nanocomponent#nanocomponentprototypeafterupdateel.
Should only require a simple restructure and not a rewrite of business logic.

At the moment we use `setTimeout` which is a _huge_ hack!

**Comment by heyitsmeuralex** [comment]
Also note that doing this for other elements would be useful as an optimization - e.g. not updating message groups.

**Comment by towerofnix** [comment]
Closing for now (see [this](https://github.com/decent-chat/decent/pull/187#issuecomment-368115464)).
