### ISSUE TITLE
Private channels

### ISSUE THREAD

**Issue by heyitsmeuralex** [decent-chat/decent#151]
Enhancement of #141. Blocked by #66.

Authorized users should be able to access private channels, whilst everyone (including deauthorized!) can access public ones. I'd imagine this shouldn't be _too_ difficult to implement 😉 

Could go along with admin-only channels - this is becoming an actual permission system!

UX-wise, it may make more sense to refer to - on a private server - private channels as 'channels' and non-private channels as 'public channels,' with an unlocked icon for public ones. If every channel is private by default, why label them? Discussion please.

**Comment by towerofnix** [comment]
(Sorry to add another label 😄)

**Comment by heyitsmeuralex** [comment]
I think we should close this issue in favour of a full blown permission system. It'll probably be easier to skip to that stage than to implement this _then_ permissions.
