### ISSUE TITLE
Move to shiny new organization

### ISSUE THREAD

**Issue by PullJosh** [decent-chat/decent#153]
Probably about time we did this. I made an org (@decent-chat) and invited all the folks.

I'm pretty certain that @towerofnix has the power to go into this repo's settings and change the owner to be the organization as a whole.

**Comment by heyitsmeuralex** [comment]
There will almost certainly be some links we need to change, in the README for example.

**Comment by PullJosh** [comment]
Github does handy redirects (see what happens with https://github.com/towerofnix/decent/), but it would be even better if we just had the links be correct. :P
