### ISSUE TITLE
Flairs

### ISSUE THREAD

**Issue by towerofnix** [decent-chat/decent#163]
Reddit-style; so, for example, "John Smith [sysadmin]" or "GodBot [bot]". (These would just be tag-like strings that display beside a username in message headings. Might want to make them colorable?)

I also want to consider *roles*. Maybe roles could simply have a "show as flair" option? That would simplify things (and also let users have more than one flair).

**Comment by heyitsmeuralex** [comment]
We should definitely defer roles for now until we come up with a more robust Discord-style permissions interface.

**Comment by heyitsmeuralex** [comment]
>Maybe roles could simply have a "show as flair" option?

I think flairs should be their own thing, and user-specific. When AT-Fun was on Discord we changed our nicknames multiple times a day, and this could be the Decent way of achieving that.

In other news, Slack has this too - it calls them **status**es. You also get an emote to pair with your flair (does Reddit have this too?)

**Comment by ktrvs** [comment]
> (does Reddit have this too?)

Yes, but it's up to the subreddit owner to enable or disable that, and choose what emojis, text, or icons can be added.

**Comment by heyitsmeuralex** [comment]
We should consider stealing the _only admins can add flairs to users_ option from Reddit, too.

**Comment by towerofnix** [comment]
Assigning myself to do API work. Note to self: this can be changed by the same endpoint as how emails are changed (which I don't actually remember oops lol). There will also need to be a WS event for flairs changing.

**Comment by heyitsmeuralex** [comment]
Already started work on this!! Including the API - see the `flairs` branch. Please don't restart :package:

**Comment by heyitsmeuralex** [comment]
It's almost complete locally.

**Comment by towerofnix** [comment]
@heyitsmeuralex Oh alright, cool! I wasn't sure if you'd actually done any API work yet.

**Comment by heyitsmeuralex** [comment]
> There will also need to be a WS event for flairs changing.

`user/update`? For general changes after we add per-user UI for example in the user list. Also we should store flairs per-message (`{ authorUsername, authorAvatarURL, authorFlair }`).
