### ISSUE TITLE
Add error codes and document API errors

### ISSUE THREAD

**Issue by heyitsmeuralex** [decent-chat/decent#182]
Currently, checking for specific server-sent errors in the client is really difficult, especially because error messages aren't documented _at all_:

```js
try {
  await api.post('register', { username, password })

  // close the modal
  modal.close()
} catch (error) {
  // handle error
  if (error.message.startsWith('username already taken')) {
    modal.showError('Username already taken')
  } else if (error.message.startsWith('password must be at least 6 characters long')) {
    modal.showError('Password must be at least 6 characters long')
  } else if (error.message.startsWith('username invalid')) {
    modal.showError('Username can contain only alphanumeric characters, underscores, and dashes')
  } else {
    // not an error from the server?
    console.error(error)
    modal.showError('Internal error')
  }

  modal.disable(false) // enable
}
```

**Ouch!** Some error handlers even use _regular expressions_. Eww.

This is also very flimsy - the error messages could change slightly, for example (as they have done recently, causing the client to display 'Internal error' when a username is taken). Starting to adhere to semver will help with this, but it'd be nice to know that error codes stay the same.

**Comment by heyitsmeuralex** [comment]
Note that just displaying `error.message` is not sufficient:

![image](https://user-images.githubusercontent.com/9429556/34964996-d9c63620-fa48-11e7-9ac8-345077ecc171.png)

**Comment by towerofnix** [comment]
(See #196.)
