### ISSUE TITLE
Put meta.decent.chat server back online

### ISSUE THREAD

**Issue by ktrvs** [decent-chat/decent#192]
I'm getting a 502 when trying to visit https://meta.decent.chat 🤔

**Comment by towerofnix** [comment]
I imagine the issue is just that @heyitsmeuralex isn't running the decent server there.

**Comment by heyitsmeuralex** [comment]
Yep.

**Comment by kyleplo** [comment]
@ktrvs Me too!

**Comment by ktrvs** [comment]
Can this be put back up now that Nanocomponents is closed?

**Comment by towerofnix** [comment]
@ktrvs :+1: Especially because of #208, since the client is now not broken.

(Although the "blocked" label has already been removed :P)

**Comment by ktrvs** [comment]
Great, I can't wait to start using it. 👍

**Comment by ktrvs** [comment]
Well, partially up now. 😄 
![1](https://user-images.githubusercontent.com/26391179/36620282-37487b68-18ea-11e8-8300-a5179ee539a2.png)

**Comment by heyitsmeuralex** [comment]
@ktrvs Yeah, I'm working on it. Having trouble with the latest build - something to do with uglify - but I'm working on it :)

**Comment by ktrvs** [comment]
@heyitsmeuralex Perfect, there's no rush. 😄

**Comment by heyitsmeuralex** [comment]
It's up! I got it to compile without tinyify; I'll be changing how we build soon.

Note that we're not using https - I got https://meta.decent.chat to redirect to the insecure form - for whatever reason that client doesn't handle `{ useSecure: true }` properly? @towerofnix could you shed any light on this?

**Comment by towerofnix** [comment]
@heyitsmeuralex Have you pulled since when you started working on putting it back online a few days ago? I think I fixed that bug [here](https://github.com/decent-chat/decent/commit/c737218737cc89f3669c22cd35a3f306d57a87a5).

**Comment by heyitsmeuralex** [comment]
Yeah, I pulled like 2 minutes ago.

**Comment by ktrvs** [comment]
@heyitsmeuralex The server seems to be down again. 🔥🌐
