### ISSUE TITLE
Clean up data returned from the API

### ISSUE THREAD

**Issue by towerofnix** [decent-chat/decent#196]
The API is just a bit messy. My thoughts on the way it Should be:

* Scrap the `success` property. Stick to HTTP status codes, and...
* Standardize `error`s. The value of `error` should be an object, `error: {code, message}`, where `message` is a human-readable message (what we currently store in `error`) and `code` is a specific, permanent identifier string (e.g. `USER_NOT_FOUND`, `NONEXISTENT_SESSION`).
* Returned data should always be an object. This is so that we can attach "extra" data, e.g. making `user-list` return `users: {}` to everybody but also `unauthorizedUsers: {}` to admins. It also makes the return value a standard type, i.e. the object dictionary; we should never just return an array or string. Finally, it makes the return data be a *specific* object, and avoids key conflicts; for example, if we return `{users: {error: {id: 123}}}`, then `error` is a property of `<response>.users` and not of `<response>` (so it doesn't look like there's an actual error with the request; there's just a key on `users` named error).

The actual specification:

```
METHOD /api/any/endpoint
-> {
  // Present only if there was an error with the request:
  error: {
    code: 'SOME_ERROR_CODE',
    message: 'There was a very bad error.'
  },

  // Present only if there was no error (these are endpoint-specific):
  prop1: [123],
  prop2: 'blah'
}
```

**Comment by towerofnix** [comment]
Error codes (wip, please discuss):

- **Authorization:**
  - `MISSING_SESSION_ID` - Not sure what to name this? This is for when the server requires authorization but you didn't pass a session ID.
  - `YET_TO_BE_AUTHORIZED` - For when the server requires authorization and the user of the session ID you passed isn't authorized yet.

**Comment by PullJosh** [comment]
Could `YET_TO_BE_AUTHORIZED` be renamed to `UNAUTHORIZED`? Or are they different?

**Comment by heyitsmeuralex** [comment]
We might want to consider collapsing `ALREADY_PINNED` and `ALREADY_REACTED` into `ALREADY_PERFORMED`.

**Comment by towerofnix** [comment]
Perhaps `NOT_OWN_MESSAGE` should be renamed to something more general, like `NOT_AUTHOR`? (But I think there could be a better name than `NOT_AUTHOR`... `NOT_OWN`, but that's not really better either!)

**Comment by heyitsmeuralex** [comment]
`NOT_YOURS`?

**Comment by heyitsmeuralex** [comment]
We should also make the error message suitable for printing - meaning proper capitalisation!

**Comment by heyitsmeuralex** [comment]
Each of these codes should have a particular HTTP code that they always come with too:
* `ALREADY_PERFORMED`: 400
* `NAME_ALREADY_TAKEN`: 400
* `YET_TO_BE_AUTHORIZED`: 403
* `MISSING_SESSION_ID`: 403
* `NOT_FOUND`: 404

**Comment by heyitsmeuralex** [comment]
Could we rename `YET_TO_BE_AUTHORIZED` to `MISSING_PERMISSIONS`? See #179
