### ISSUE TITLE
Use SQLite instead of NeDB

### ISSUE THREAD

**Issue by eq** [decent-chat/decent#2]
sqlite is good and nice

**Comment by towerofnix** [comment]
Why? I've never worked with sqlite before, whereas I have with nedb, so writing code with nedb is a lot easier and faster for me.

**Comment by towerofnix** [comment]
Somebody made a backend tag, so, :woman_shrugging:

**Comment by towerofnix** [comment]
Removing "help wanted" because I am not in a position where I want help :)
