### ISSUE TITLE
"You are deauthorized" message

### ISSUE THREAD

**Issue by TheInitializer** [decent-chat/decent#202]
When a logged-in user is deauthorized, they have no way of knowing that they are, other than that their messages stop showing up, channel messages stop loading and pretty much everything stops working.

The user should probably be automatically logged out, and shown a "you were deauthorized from this server" message.

**Comment by towerofnix** [comment]
Really? I thought we had a specific deauthorization view (where it would show a server-specific message in the sidebar).. looks like that was broken on the client at some point.
