### ISSUE TITLE
Various branches still use the old Bantisocial README.md file

### ISSUE THREAD

**Issue by ktrvs** [decent-chat/decent#211]
A handful of branches still use the old Bantisocial README - `serviceworkers` and `unread-notifs`, to be exact.

Also, the `vue` and `backend-stuff` branches use an older decent README, where the header text is centred.

**Comment by heyitsmeuralex** [comment]
These branches are old and we, most likely, won't come back to them. They're there in-case we need them again :)

**Comment by ktrvs** [comment]
@heyitsmeuralex Ah, okay. 👍
