### ISSUE TITLE
Are email addresses made public by avatar URLs?

### ISSUE THREAD

**Issue by towerofnix** [decent-chat/decent#218]
There's no immediate way to simply view a user's email (outside of poking at the database, as the sysadmin), but is it possible to figure out what a user's email is based on their avatar URL?

This isn't necessarily a bad thing, but if it *is* possible, it should be visibly noted next to the email input in the account settings page.

**Comment by heyitsmeuralex** [comment]
Avatar URLs are made by md5-hashing the user's email address. Pretty sure this is a non-issue.
