### ISSUE TITLE
Changed profile pictures should reflect in user list sidebar

### ISSUE THREAD

**Issue by towerofnix** [decent-chat/decent#223]
At the moment, the old profile picture will be used until the page is reloaded.

Thanks for spotting this, @eq!

**Comment by heyitsmeuralex** [comment]
Emotes also don't update without reloads, as far as I'm aware.

**Comment by heyitsmeuralex** [comment]
Just suggested `user/update` as a new WS event in #163 - we could use that here.

**Comment by TheInitializer** [comment]
On a related note, when a user changes their profile picture it only applies to the messages sent *after* the profile picture change. This may be by design - `avatarURL` is stored individually with each message - but I thought that was just so that you don't have to make a request to /users/:userID every time a new message is sent.

Is is a bug or a feature? 📦

**Comment by towerofnix** [comment]
@TheInitializer Honestly I'd call it a bug at this point. Once we have events for profile pictures changing, we won't even need to check the avatar URL stored on the message; we can just check our user map for the avatar URL of the user whose ID is the message's author ID. So we can remove avatarURLs from messages once we've got the ws event!

**Comment by heyitsmeuralex** [comment]
I disagree, I'd call it a feature.

Discord does it like this too.

---

Avatars are changed via email - to change that you use the same endpoint as added in the pr, causing user/update. So this is fixed.

**Comment by towerofnix** [comment]
@TheInitializer @heyitsmeuralex Actually yeah. I have some ideas for things to do with dynamic profile pictures (did you see that discussion?), which definitely require per-message avatar URLs.

I like keeping avatar URLs specific to the message, anyways: old "Wow, your avatar looks like..." and similar messages make more sense the way it is right now.
