### ISSUE TITLE
Sidebars should be scrollable

### ISSUE THREAD

**Issue by towerofnix** [decent-chat/decent#227]
Who wants to CSS position-sticky headers like "users" and "channels", which is now [supported on everything](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Browser_compatibility)? Or maybe that's a dumb idea :P

Blocked by #226, but could be implemented into that (ping @heyitsmeuralex, feel free to unassign yourself if you don't want to do this in that PR).

**Comment by heyitsmeuralex** [comment]
Pretty sure we're going to do actual CSS _changes_ outside of #226.
