### ISSUE TITLE
Scrollback is somewhat broken

### ISSUE THREAD

**Issue by towerofnix** [decent-chat/decent#235]
I think the problem has to do with the scroll's Y-position not effectively being set, maybe because a scroll is already in progress... I noticed that it only happens on really, really fast connections, i.e. to localhost, and not on meta.decent.chat. This lines up with my thoughts because, by the time the older messages have been fetched, the scroll animation is finished.

**Comment by heyitsmeuralex** [comment]
I think we really need to rethink a lot of the code surrounding the messages list - there's a ton of bugs, and we need to think about scrollforward too.

**Comment by PullJosh** [comment]
The clear solution is to add 250ms of artificial delay to all API calls.

**Comment by heyitsmeuralex** [comment]
>thumbs up

**Comment by PullJosh** [comment]
Solved in the preact client.
