### ISSUE TITLE
All colors washed out

### ISSUE THREAD

**Issue by ktrvs** [decent-chat/decent#244]
The server add button currently looks like:
![1](https://user-images.githubusercontent.com/26391179/36814410-5009dce4-1ccf-11e8-860b-33d1b8d2099a.png)

It may just be me, but I find it pretty hard to see properly, so It may be a good idea to change up the colors a bit.

Note: It gets even worse when hovered over.

**Comment by heyitsmeuralex** [comment]
![image](https://user-images.githubusercontent.com/9429556/36815302-35432bce-1cd2-11e8-8773-9b0b2871260f.png)

What browser is this?

**Comment by ktrvs** [comment]
Firefox 58, MacOS 10.13.3. 🤔

**Comment by heyitsmeuralex** [comment]
I'm on FF developer edition, 59. Can you screenshot the entire page?

**Comment by ktrvs** [comment]
Yep. 👍 

![1](https://user-images.githubusercontent.com/26391179/36815608-293b062a-1cd3-11e8-8850-98ec181660a5.png)
![2](https://user-images.githubusercontent.com/26391179/36815607-2914a5e8-1cd3-11e8-9be1-44917bcae2b5.png)

**Comment by heyitsmeuralex** [comment]
Ew, what the hell? **Every single colour is washed out**.

**Comment by ktrvs** [comment]
@heyitsmeuralex Yeah, it may be a Firefox Quantum issue. I remember everything being darker on chrome, and I just tried safari:
![1](https://user-images.githubusercontent.com/26391179/36815757-a5a4e2a8-1cd3-11e8-8733-074f3da48d3a.png)

**Comment by heyitsmeuralex** [comment]
I'm on FF Quantum though. I'd wager it's a bug in 58?
Could you try installing FF Developer Edition and see if it persists there?

**Comment by ktrvs** [comment]
@heyitsmeuralex Exactly what I was doing. 😄

**Comment by ktrvs** [comment]
@heyitsmeuralex I can confirm that it doesn't seem to be an issue on FF Developer Edition:
![1](https://user-images.githubusercontent.com/26391179/36816075-a74a8594-1cd4-11e8-80cc-5e492e1ea473.png)
