### ISSUE TITLE
WS events recieved before the client responds to pingdata aren't reacted to

### ISSUE THREAD

**Issue by heyitsmeuralex** [decent-chat/decent#245]
...I think. Maybe not?

Regardless, something's super buggy about the WS class.

**Comment by heyitsmeuralex** [comment]
We really, really, **really** need to fix this @towerofnix. It's annoying.

**Comment by towerofnix** [comment]
@heyitsmeuralex - Cool. Glad you've figured out exactly what the issue is now. This is a lot more fixable now.
