### ISSUE TITLE
Add API endpoint for deleting channels

### ISSUE THREAD

**Issue by PullJosh** [decent-chat/decent#263]
This would be useful if, hypothetically, an admin user created a meme channel on a whim and then realized it wasn't actually a good idea. Hypothetically.

**Comment by towerofnix** [comment]
This [already exists](https://github.com/decent-chat/decent/blob/master/docs/api.md#delete-a-channel-delete-apichannelsid) actually! `DELETE /api/channels/:channelID {sessionID}`.
