### ISSUE TITLE
Add CODE OF CONDUCT file

### ISSUE THREAD

**Issue by joker314** [decent-chat/decent#291]
It would be awesome if we added a `CODE OF CONDUCT.md` file to this repository. It's similar to the `LICENCE`, `README`, etc. files. It states that you need to be nice to everyone when you contribute here else you'll be blocked. Should one be added?

**Comment by PullJosh** [comment]
> It states that you need to be nice to everyone when you contribute here.

I'm totally in favor of being nice, but it always feels a little patronizing to state it explicitly. Plus, is someone really going to change their mind about how they choose to engage with other contributors because we have a markdown file telling them what to do included in our source?

**Comment by joker314** [comment]
@PullJosh, it makes it clear that we'll ban users from doing anything if they violate the rules, and provides an email address for reporting issues when things do go wrong (which they do). Perhaps the rules won't stop someone, but they'll make it easier to take actions afterwards.

**Comment by joker314** [comment]
Here is an example Code of Conduct, quite widespread: https://www.contributor-covenant.org/

**Comment by heyitsmeuralex** [comment]
I already considered this, and it honestly feels like a non-issue at the moment. Plus, we don't have an email address (`team@decent.chat` would be nice; if anyone knows how to set up a mailserver on Linux, your help is wanted) to direct people to.

If Decent becomes substantially popular or something comes up, we can bring this in. I don't really feel like having extra files in the repo is worth it right now.

Anyone object to closing this for now?

**Comment by ktrvs** [comment]
@heyitsmeuralex How about [this](https://www.rainloop.net/)?

**Comment by heyitsmeuralex** [comment]
@ktrvs that's a webmail client - I'm talking about a mailserver (IMAP, SMTP).
