### ISSUE TITLE
Consider using the MPL license

### ISSUE THREAD

**Issue by heyitsmeuralex** [decent-chat/decent#293]
Currently we use the GPL, which is a really strong copyleft license. The [Mozilla Public License](https://choosealicense.com/licenses/mpl-2.0/) is similar, but larger works may use/fork the software without providing its sourcecode. This is mostly important for bots (decent.js) as I can't imagine many people writing Decent bots using decent.js would want to release the sourcecode, as its only a library.

>  Permissions of this weak copyleft license are conditioned on making available source code of licensed files and modifications of those files under the same license (or in certain cases, one of the GNU licenses). Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. **However, a larger work using the licensed work may be distributed under different terms and without source code for files added in the larger work.**

Opinions?

**Comment by PullJosh** [comment]
I'm certainly no legal expert, but this seems like a fine change. I guess the distinction for me is that if you're using the Decent code to achieve some goal (like making a bot), that shouldn't need to be open source, but if you're modifying Decent itself to become something new, it should.

**Comment by heyitsmeuralex** [comment]
> Currently we use the GPL, which is a really strong copyleft license. The Mozilla Public License is similar, but larger works may use/fork the software without providing its sourcecode.

@towerofnix @TheInitializer @joker314 @ktrvs  is this ok with you guys?

Pretty sure going for a different license requires all existing contributors to agree.

**Comment by joker314** [comment]
@heyitsmeuralex pretty sure that's not true; but I'm no lawyer!

As long as people are Free with relation to this unmodified version, then I'm happy. LGTM

**Comment by towerofnix** [comment]
@heyitsmeuralex Sure, this sounds good to me.

**Comment by ktrvs** [comment]
@heyitsmeuralex Seems good. 👍
